[Distribution]
Distribution=fedora
Release=rawhide

[Output]
Format=none

[Content]
Bootable=no
BuildPackages=
        coreutils
        inkscape
        latexmk
        make
        texlive-amsfonts
        texlive-enumitem
        texlive-geometry
        texlive-graphics
        texlive-hyperref
        texlive-latex-bin
        texlive-svg
        texlive-tools

[Build]
BuildDirectory=mkosi.output
BuildKey=-
BuildSourcesEphemeral=yes
CacheDirectory=mkosi.cache
Incremental=yes
